server:
  port: 9090

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

team:
  ext:
    url: https://apiv2.apifootball.com/?
    api-key: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978
